apiVersion: v1
kind: Service
metadata:
  namespace: vote
  labels:
    app: result
  name: result
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: result
  type: NodePort
