apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result
  namespace: vote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image:  us.gcr.io/devops-getup/result
        name: result
