apiVersion: v1
kind: Service
metadata:
  namespace: vote
  labels:
    app: vote
  name: vote
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
  type: NodePort
